# Generated by Django 4.2.4 on 2023-08-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_auto_20220417_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(max_length=4000, verbose_name='توضیحات اسلایدر'),
        ),
    ]
